### ISSUE TITLE
InvalidCastException when using RDom.CSharp.LoadGroup

### ISSUE THREAD

**Issue by flq** [KathleenDollard/RoslynDOM#104]
I have a solution where for practically all projects I am iterating over to load a root group I get the following error:

`Unable to cast object of type 'RoslynDom.RDomStructuredDocumentation' to type 'RoslynDom.Common.IStatementAndDetail'.`

at

```
   at System.Linq.Enumerable.<CastIterator>d__b1`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RoslynDom.Common.RDomCollection`1.CreateAndAdd[TInput](TInput input, Func`2 createDeleg)
   at RoslynDom.Common.RDomCollection`1.CreateAndAdd[TInput](IEnumerable`1 input, Func`2 createDeleg)
   at RoslynDom.CSharp.CreateFromWorker.InitializeStatements(IStatementBlock itemAsStatement, SyntaxNode syntaxNode, IDom parent, SemanticModel model)
   at RoslynDom.CSharp.RDomConstructorTypeMemberFactory.CreateItemFrom(SyntaxNode syntaxNode, IDom parent, SemanticModel model)
   at RoslynDom.CSharp.RDomBaseSyntaxNodeFactory`2.CreateListFrom(SyntaxNode syntaxNode, IDom parent, SemanticModel model)
   at RoslynDom.CSharp.RDomBaseSyntaxNodeFactory`2.CreateListFromInterim(SyntaxNode syntaxNode, IDom parent, SemanticModel model)
   at RoslynDom.CSharp.RDomBaseSyntaxNodeFactory`2.CreateFrom(SyntaxNode syntaxNode, IDom parent, SemanticModel model, Boolean skipWhitespace)
   at RoslynDom.RDomCorporation.Create(SyntaxNode node, IDom parent, SemanticModel model, Boolean skipDetail)
   at RoslynDom.CSharp.RDomClassTypeMemberFactory.<>c__DisplayClass5_0.<CreateListFromInterim>b__1(MemberDeclarationSyntax x)
   at RoslynDom.Common.RDomCollection`1.CreateAndAdd[TInput](TInput input, Func`2 createDeleg)
   at RoslynDom.Common.RDomCollection`1.CreateAndAdd[TInput](IEnumerable`1 input, Func`2 createDeleg)
   at RoslynDom.Common.RDomCollection`1.CreateAndAdd[TInput,TRaw](TInput input, Func`2 getItemsDeleg, Func`2 createDeleg)
   at RoslynDom.CSharp.RDomClassTypeMemberFactory.CreateListFromInterim(SyntaxNode syntaxNode, IDom parent, SemanticModel model)
   at RoslynDom.CSharp.RDomBaseSyntaxNodeFactory`2.CreateFrom(SyntaxNode syntaxNode, IDom parent, SemanticModel model, Boolean skipWhitespace)
   at RoslynDom.RDomCorporation.Create(SyntaxNode node, IDom parent, SemanticModel model, Boolean skipDetail)
   at RoslynDom.CSharp.CreateFromWorker.<>c__DisplayClass20_0.<LoadStemMembers>b__1(MemberDeclarationSyntax x)
   at RoslynDom.Common.RDomCollection`1.CreateAndAdd[TInput](TInput input, Func`2 createDeleg)
   at RoslynDom.Common.RDomCollection`1.CreateAndAdd[TInput](IEnumerable`1 input, Func`2 createDeleg)
   at RoslynDom.CSharp.CreateFromWorker.LoadStemMembers(IStemContainer newItem, IEnumerable`1 memberSyntaxes, IEnumerable`1 usingSyntaxes, SemanticModel model)
   at RoslynDom.CSharp.RDomNamespaceStemMemberFactory.CreateItemFrom(SyntaxNode syntaxNode, IDom parent, SemanticModel model)
   at RoslynDom.CSharp.RDomBaseSyntaxNodeFactory`2.CreateListFrom(SyntaxNode syntaxNode, IDom parent, SemanticModel model)
   at RoslynDom.CSharp.RDomBaseSyntaxNodeFactory`2.CreateListFromInterim(SyntaxNode syntaxNode, IDom parent, SemanticModel model)
   at RoslynDom.CSharp.RDomBaseSyntaxNodeFactory`2.CreateFrom(SyntaxNode syntaxNode, IDom parent, SemanticModel model, Boolean skipWhitespace)
   at RoslynDom.RDomCorporation.Create(SyntaxNode node, IDom parent, SemanticModel model, Boolean skipDetail)
   at RoslynDom.CSharp.CreateFromWorker.<>c__DisplayClass20_0.<LoadStemMembers>b__1(MemberDeclarationSyntax x)
   at RoslynDom.Common.RDomCollection`1.CreateAndAdd[TInput](TInput input, Func`2 createDeleg)
   at RoslynDom.Common.RDomCollection`1.CreateAndAdd[TInput](IEnumerable`1 input, Func`2 createDeleg)
   at RoslynDom.CSharp.CreateFromWorker.LoadStemMembers(IStemContainer newItem, IEnumerable`1 memberSyntaxes, IEnumerable`1 usingSyntaxes, SemanticModel model)
   at RoslynDom.CSharp.RDomRootFactory.CreateItemFrom(SyntaxNode syntaxNode, IDom parent, SemanticModel model)
   at RoslynDom.CSharp.RDomBaseSyntaxNodeFactory`2.CreateListFrom(SyntaxNode syntaxNode, IDom parent, SemanticModel model)
   at RoslynDom.CSharp.RDomBaseSyntaxNodeFactory`2.CreateListFromInterim(SyntaxNode syntaxNode, IDom parent, SemanticModel model)
   at RoslynDom.CSharp.RDomBaseSyntaxNodeFactory`2.CreateFrom(SyntaxNode syntaxNode, IDom parent, SemanticModel model, Boolean skipWhitespace)
   at RoslynDom.RDomCorporation.Create(SyntaxNode node, IDom parent, SemanticModel model, Boolean skipDetail)
   at RoslynDom.CSharp.RDomCompilationFactory.CreateFrom(Compilation compilation, Boolean skipDetail)
   at RoslynDom.RDomCorporation.CreateCompilation(Compilation compilation, IDom parent, SemanticModel model, Boolean skipDetail)
   at RoslynDom.CSharp.RDom.LoadGroupFromInternal(Compilation compilation, SyntaxTree[] trees)
   at RoslynDom.CSharp.RDom.LoadGroup(Project project)
   at ReFuc.DOMHub.<SelectByProjects>b__0(Project p) in c:\DotNetEntwicklung\ReFuc\ReFuc\Program.cs:line 63
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ReFuc.Program.Main(String[] args) in c:\DotNetEntwicklung\ReFuc\ReFuc\Program.cs:line 42
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

At first glance I do not see what could be strange about the projects.

It would be interesting to know if you have any idea about this one.

Regards

**Comment by flq** [comment]
If an exception is thrown, but nobody witnesses the consequences, did it ever happen?
